config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do
    member do
      put "like" => 'posts#like'
    end
  end
  # root 'pages#index'
  root 'pages#home'
  get '/home'=>'pages#home' #override default route
  get '/user/:id'=>'pages#profile'
  get '/explore'=>'pages#explore'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum:140} # tweets are capped at 140 chars.
  default_scope -> { order(created_at: :desc) } #display new tweet first
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord  
  acts_as_voter


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
 
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
         
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
 
  def following?(user)
    following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #call the configured params
    before_action :configure_permitted_parameters, if: :devise_controller?

    # protect database,while allowing this fields to be updated
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me]) 
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email, :password, :password_confirmation, :remember_me])
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :remember_me])
    end

end

app/controllers/pages_controller.rb
#The pages controller contain all of the code for any pages inside of /pages
class PagesController < ApplicationController
  
  #back end code for pages/index
  def index
  end

  #back end code for pages/home
  def home
    @posts=Post.all
    @newPost=Post.new
  end

  #back end code for pages/profile
  def profile
    # grab the username from the URL as :id
    if (User.find_by_username(params[:id]))
      @username = params[:id]
    else
      redirect_to root_path, :notice=> "User not found!"
    end
    @posts=Post.all.where("user_id = ?",User.find_by_username(params[:id]).id)
    @newPost=Post.new
  end

  #back end code for pages/explore
  def explore
    @posts=Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [ :like ]
    respond_to :js, :json, :html
    def new
        @post =Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        respond_to do |format|
            if (@post.save)
                format.html { redirect_to "", notice: "Post was successfully created." }
            else
                format.html { redirect_to "", notice: "Error." }
            end
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
     
        respond_to do |format|
          format.html { redirect_to "" }
          format.json { head :no_content }
       end
     end
     
    def like
        @post = Post.find(params[:id])
        if !current_user.liked? @post
            @post.liked_by current_user
        elsif current_user.liked? @post
            @post.unliked_by current_user
        end
    end

    private

    # Only allow a list of trusted parameters through.
    def post_params
        params.require(:post).permit(:user_id,:content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<!-- we will render saperate navbars depending on if the user is signed in or not -->

<% if !user_signed_in? %>
    <%= render 'layouts/nav_guest' %>
<% else %>
    <%= render 'layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to image_tag('/img/logo.png',class:"logo",height:"50",alt:'logo'), root_path ,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", home_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Explore", explore_path, class:"nav-link" %>
      </li>

      
    </ul>
    
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav ">
        <li class="nav-item" >
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Navigation
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign In", new_user_session_path, class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
             <%= link_to "Sign Up", new_user_registration_path, class:"dropdown-item" %>
          </div>
        </li>

      </ul>
  </div>
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid container">
    <%= link_to image_tag('/img/logo.png',class:"logo",height:"50",alt:'logo'), root_path ,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", home_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Explore", explore_path, class:"nav-link" %>
        </li>

        
      </ul>
      
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search Twitter" aria-label="Search">
      </form>
      <ul class="navbar-nav ">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/user/<%= current_user.username %>">Profile</a>
              <%= link_to "Settings", edit_user_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </li>
          
          <!-- <li class="nav-item" >
            <a class="nav-link disabled" href="#">Disabled</a>
          </li> -->

        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/3ec71fc36c.js" crossorigin="anonymous"></script>

    <title>Twitter</title>

  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <span class="notice"><%= notice %></span>
       <span class="alert"><%= alert %></span>
        <%= yield %>
    </div>
      


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function () {
          $('.dropdown-toggle').dropdown();
      });
  </script>
  </body>
</html>

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/home.html.erb
  <br/>
  <br>
  <div class="row">
    <div class="col">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if user_signed_in? %>
          <p class="side-panel">
            <div class="col-sm-12" style="margin-top: 10px;">
              <div class="col-sm-2"><img src="/public/img/no_image.png" height="50px" width="50px" class="rounded-img home-avatar">
            </div>
              <div class="col-sm-10"><h4 style="text-align: center;"><%= current_user.username %></h4></div>
              <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">POSTS<br>
                <h6 style="color: #0084B4; font-size: 200%;"><%= current_user.posts.count %></h6>
              </div>
              <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">FOLLOWERS<br>
                <h6 style="color: #0084B4; font-size: 200%;">followers count</h6>
              </div>
            </div>
          </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-6">
      <% if user_signed_in? %>
      <%= render '/components/post_form' %> <br/>
      <% end %>
      <% @posts.each do |p| %>
      <div class="panel panel-default post-panel">
        <div class="panel-body">
          <div class="col-sm-1">
            <%= image_tag "/img/no_image.png", style: 'height:50px;width:50px;margin-top:15px;margin-bottom:15px;'%>
          </div>
          <div class="col-sm-11">
            <p class="post-title">
              <span class='post-owner'><%= User.find(p.user_id).username %> </span>
              - <small class='post-time'><%= p.created_at.to_formatted_s(:short)%></small>
            </p>
            <p class="post-content">
              <%= p.content %>
            </p>
          </div>
          <div class="col-sm-12">
            <p class="post-link">
              <a href="" class="post-img"><i class="fas fa-reply"></i></a>
              <a href="" class="post-img"><i class="fas fa-retweet"></i></a>
              
              <%= link_to like_post_path(p.id) ,class:'like-btn' , method: :put, remote: :true do %>
                <a href="" class="post-img"><i class="far fa-heart"></i></a>
              <% end %>
              <span class='likes-count'><%= @post.get_upvotes.size %></span>
              <a href="" class="post-img"><i class="fas fa-pencil-alt"></i></a>
            </p>
          </div>
        </div>
        </div>
        <br/>
      <% end %>
    </div>
  
    <div class="col">
      <div class="panel panel-default">
        <div class="panel-body">
          <p class="side-panel">about</p>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-body">
          <p class="side-panel" style="opacity: 50%;">
            <small>
              Terms of Service
            Privacy Policy
            Cookie Policy
            Ads info
            More
            © 2021 Twitter, Inc.
            </small>
          </p>
        </div>
      </div>
    </div>
  </div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/like.js.erb
<% if current_user.liked? @post %>
  $('.like-btn').addClass('liked')
<%else%>
  $('.like-btn').addClass('like-btn')
<% end %>
$('.likes-count').html("<%= @post.get_upvotes.size %>")

app/views/pages/profile.html.erb
  <br/>
  <div class="row">
    <div class="col">
      <div class="jumbotron">
          <img src="/public/img/logo.png" height="200px" width="200px" class="rounded-img">
            <h3 style="font-weight: bold;"><%= params[:id] %></h3>

        </div>
    </div>
</div>



<br/>
<div class="row">
  <div class="col">
    
  </div>
  <div class="col-6">
    <% @posts.each do |p| %>
    <div class="panel panel-default post-panel">
      <div class="panel-body">
        <div class="col-sm-1">
          <%= image_tag "/img/no_image.png", style: 'height:50px;width:50px;margin-top:15px;margin-bottom:15px;'%>
        </div>
        <div class="col-sm-11">
          <p class="post-title">
            <span class='post-owner'><%= User.find(p.user_id).username %> </span>
            - <small class='post-time'><%= p.created_at.to_formatted_s(:short)%></small>
          </p>
          <p class="post-content">
            <%= p.content %>
          </p>
        </div>
        <div class="col-sm-12">
          <p class="post-link">
              <a href="" class="post-img"><i class="fas fa-reply"></i></a>
              <%= link_to '', {:controller=>:posts,:action=>:destroy, :id=>p.id}, :method=>:delete, class:"post-img fas fa-trash" %>
              <a href="" class="post-img"><i class="far fa-heart"></i></a>
              <a href="" class="post-img"><i class="fas fa-pencil-alt"></i></a>
          </p>
        </div>
      </div>
      </div>
      <br/>
    <% end %>
  </div>

  <div class="col">
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="side-panel">about</p>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="side-panel" style="opacity: 50%;">
          <small>
            Terms of Service
          Privacy Policy
          Cookie Policy
          Ads info
          More
          © 2021 Twitter, Inc.
          </small>
        </p>
      </div>
    </div>
  </div>
</div>